config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  resources :contacts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  def render_not_found
  	render :file => 'public/404.html', :status => :not_found, :layout => false if @contact.blank?
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	before_action :authenticate_user!
	before_filter :load_contact, :only => [:show, :edit, :destroy, :update]
	
	def index
		@contacts = current_user.present? ? current_user.contacts : []
	end

	def show
	end

	def edit
	end

	def destroy
	end

	def create
		@contact = current_user.contacts.new(contact_params)
		if @contact.save
			redirect_to @contact, :notice => "Contact succeefully added"
		else
			render :new
		end
	end

	def update
		if @contact.update(contact_params)
      redirect_to @contact, notice: 'Contact was successfully updated.'
    else
      redirect_to edit_contact_path(@contact), notice: 'Could not update the Contact'
    end
	end

	def new
		@contact = current_user.contacts.new
	end

	private

	def load_contact
		@contact = Contact.find_by_id(params[:id]) or render_not_found
	end

	def contact_params
    params.require(:contact).permit(:name, :primary_number, :office_number, :city, :email, :address, :company, :dob, :user_id)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

	def index
		redirect_to contacts_path if current_user.present?
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_contact.html.erb
<%= form_for @contact do |f| %>
  <% if @contact.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this Contact from being saved:</h2>
          <ul>
            <% @contact.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
  <div class="main-container">
    <div class="contact-left">
      <p>
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </p>
     
      <p>
        <%= f.label :primary_number %><br>
        <%= f.text_field :primary_number %>
      </p>

      <p>
        <%= f.label :office_number %><br>
        <%= f.text_field :office_number %>
      </p>

      <p>
        <%= f.label :city %><br>
        <%= f.text_field :city %>
      </p>
    </div>

    <div class="contact-rigth">
      <p>
        <%= f.label :email %><br>
        <%= f.email_field :email %>
      </p>

      <p>
        <%= f.label :address %><br>
        <%= f.text_field :address %>
      </p>

      <p>
        <%= f.label :company %><br>
        <%= f.text_field :company %>
      </p>

      <p>
        <%= f.label :dob %><br>
        <%= f.date_select :dob %>
      </p>

      <p>
        <%= f.submit %>
      </p>
    </div>
  </div>
<% end %>

app/views/contacts/index.html.erb
<% if current_user.present? %>
	<h3>Welcome <%= current_user.first_name %></h3>
<% else %>
	<h3>Welcome Guest</h3>
<% end %>

<% if @contacts.blank? %>
	<p>You dont have any contact Yet</p>
<% else %>
	<% @contacts.each do |contact| %>
		<div class="contact-container">
			<div class="field">
				<label> Name: <%= contact.name %> </label>
			</div>
			<div class="field">
				<label> Email: <%= contact.email %> </label>
			</div>
			<div class="field">
				<label> Phone: <%= contact.primary_number %> </label>
			</div>
			<div class="field">
				<%= link_to contact_path(contact) do %>
				 <span> View full details </span>
				<% end %>
			</div>
		</div>
	<% end %>
<% end %>

<%= link_to new_contact_path do %>
	<span style="float: right;"> Add a new Contact </span>
<% end %>

app/views/contacts/new.html.erb
<%= render :partial => 'contact' %>

app/views/contacts/show.html.erb
<%= render :partial => 'contact' %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Edit account', edit_user_registration_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link' %></li>
<% else %>
  <li class='nav-item'><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container">
  <nav class="navbar navbar-dark bg-inverse">
    <ul class="nav navbar-nav clearfix">
      <li class="nav-item">
        <button class="navbar-toggler hidden-sm-up nav-link" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
          &#9776;
        </button>
      </li>
    </ul>
    <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
      <%= link_to "Home", root_path, class: 'navbar-brand' %>
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<li class='nav-item'><%= link_to 'About', page_path('about'), class: 'nav-link' %></li>
<li class='nav-item'><%= link_to 'Reach US', page_path('reach_us'), class: 'nav-link' %></li>
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Contacts', contacts_path, class: 'nav-link' %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Contact App" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Contact App" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This application is used to manage the user contacts, user can <%= link_to 'SignUp', new_user_registration_path, class: 'nav-link' %></li> or <%= link_to 'SignIn', new_user_session_path, class: 'nav-link' %></li> to view your contacts.
</p>

app/views/pages/reach_us.html.erb
<% content_for :title do %>Reach Us<% end %>
<h3>Contact Details</h3>
<p>
Write us for any feedback or suggestions. </br></br>
<a href="mailto:support@contact.com"> Send Email </a>
</p>

app/views/users/_user.html.erb
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<% if current_user %>
	<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>
<% else %>
	<p><%= link_to 'Log in', new_user_session_path %> or <%= link_to 'Sign up', new_user_registration_path %> to view your contacts</p>
<% end %>